spring:
  application:
    name: discovery
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${EUREKA_SERVER_URL}:${PORT}/eureka/
server:
  port: ${PORT}