spring:
  application:
    name: discovery
  cloud:
    config:
      enabled: false
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${EUREKA_SERVER_URL}/eureka/
server:
  port: ${PORT}